"""Perfiles técnicos que impiden que las clases cambien solo de nombre.

Cada curso declara una cadena funcional, un principio dominante, un caso de
estudio, un riesgo y una decisión. La capa pedagógica combina estos datos con
el contenido técnico ya escrito en cada documento.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Perfil:
    cadena: tuple[str, str, str, str]
    principio: str
    caso: str
    riesgo: str
    contraste: str
    decision: str


PERFILES: dict[str, Perfil] = {
    "motos": Perfil(("motor", "embrague y caja", "transmisión final", "neumático trasero"), "equilibrio entre inclinación, velocidad, radio y adherencia disponible", "aproximación a una curva urbana mojada con visibilidad parcial", "agotar adherencia por frenar o acelerar bruscamente con la moto inclinada", "scooter urbano frente a motocicleta trail", "ajustar velocidad, trayectoria y suavidad de los mandos antes de inclinar"),
    "automoviles": Perfil(("motor", "transmisión", "diferencial", "ruedas motrices"), "transferencia de carga y reparto del círculo de adherencia entre frenar, girar y acelerar", "frenada de emergencia en una calzada con adherencia desigual", "perder estabilidad por combinar exceso de velocidad, giro y frenado tardío", "tracción delantera frente a tracción trasera", "crear margen de detención y dosificar dirección y freno según la superficie"),
    "formula-1": Perfil(("unidad de potencia", "caja secuencial", "diferencial", "neumáticos"), "interacción entre carga aerodinámica, temperatura del neumático y balance del monoplaza", "entrada y salida de una curva rápida durante una tanda con neumáticos degradados", "sobrepasar el agarre disponible al cambiar el balance con freno, volante o acelerador", "configuración de alta carga frente a baja carga aerodinámica", "sacrificar velocidad de entrada para conservar estabilidad y tracción de salida"),
    "buses": Perfil(("motor", "transmisión", "freno de servicio y retardador", "ejes"), "gestión de inercia, distancia de detención y transferencia de peso con pasajeros", "descenso prolongado con el vehículo cargado y una parada próxima", "sobrecalentar los frenos o provocar caídas de pasajeros con acciones bruscas", "bus urbano frente a autocar interurbano", "seleccionar marcha y retardador antes de que la velocidad obligue a abusar del freno"),
    "camiones": Perfil(("motor", "caja de cambios", "árbol y diferencial", "ruedas motrices"), "relación entre masa, pendiente, energía cinética y capacidad térmica de frenado", "descenso de montaña con carga cercana al máximo autorizado", "embalamiento, fatiga de frenos o pérdida de estabilidad de la carga", "camión rígido frente a tractocamión articulado", "planificar velocidad y relación de transmisión antes de entrar en la pendiente"),
    "tanques": Perfil(("motor", "transmisión", "ruedas tractoras", "orugas"), "tracción y presión sobre el terreno condicionadas por masa, reparto y resistencia al avance", "cruce simulado de suelo blando con cambio de pendiente", "atasco, pérdida de movilidad o exposición por elegir una ruta incompatible", "carro pesado frente a vehículo blindado ligero", "reconocer capacidad del terreno y escoger ruta, velocidad y orientación del casco"),
    "ascensores": Perfil(("motor", "polea tractora", "cables", "cabina y contrapeso"), "equilibrio de masas y control de aceleración, velocidad, nivelación y frenado", "viaje con carga variable seguido de una orden de parada en piso", "movimiento con puertas inseguras, mala nivelación o pérdida de tracción", "ascensor de tracción frente a ascensor hidráulico", "verificar enclavamientos y estado antes de autorizar el movimiento"),
    "tren-pasajeros": Perfil(("captación o motor", "convertidor de tracción", "motores de eje", "rueda-carril"), "adherencia rueda-carril, curva de frenado y cumplimiento de señales", "aproximación a estación con lluvia y alta ocupación", "rebasar el punto de parada o comprometer la comodidad por frenar tarde", "unidad eléctrica múltiple frente a tren remolcado", "anticipar la frenada según señal, pendiente, adherencia y carga"),
    "tren-alta-velocidad": Perfil(("catenaria", "electrónica de potencia", "motores distribuidos", "rueda-carril"), "estabilidad dinámica y crecimiento de la energía con el cuadrado de la velocidad", "reducción de velocidad previa a una zona de viento lateral", "perder margen por interpretar tarde una restricción a velocidad elevada", "tracción distribuida frente a cabezas tractoras", "cumplir la curva de frenado con anticipación y sin correcciones bruscas"),
    "tren-carga": Perfil(("locomotora", "generador y tracción", "enganches", "rueda-carril"), "fuerzas longitudinales del tren y propagación del freno neumático", "arranque de un tren largo en rampa con holguras entre enganches", "rotura de enganche, patinaje o compresión excesiva del convoy", "carga unitaria frente a carga mixta", "aplicar potencia y freno de modo gradual considerando la longitud completa"),
    "gruas": Perfil(("motor", "bombas hidráulicas", "cabrestante y pluma", "gancho y carga"), "momento de vuelco igual a carga por radio, condicionado por apoyos y configuración", "izaje de una carga conocida cuyo destino exige aumentar el radio", "exceder la tabla de carga o perder estabilidad del apoyo", "grúa móvil telescópica frente a grúa de celosía", "confirmar peso, radio, configuración y suelo antes de levantar"),
    "grua-portuaria": Perfil(("alimentación", "accionamientos", "carro y cables", "spreader y contenedor"), "control del péndulo y productividad sin superar límites estructurales ni de viento", "traslado de un contenedor desde buque con ráfagas laterales", "oscilación, enganche incompleto o ingreso de personas al área de caída", "grúa pórtico STS frente a grúa móvil portuaria", "detener o suavizar el ciclo según viento, señalización y estabilidad de la carga"),
    "grua-torre": Perfil(("alimentación", "cabrestante", "carro y pluma", "gancho y carga"), "equilibrio de momentos: el efecto de la carga crece cuando aumenta su radio", "traslado de una carga desde radio corto hacia el extremo de pluma", "sobrepasar capacidad, inducir péndulo o trabajar sobre una zona no aislada", "grúa de pluma horizontal frente a pluma abatible", "consultar tabla de carga y viento antes de autorizar cada trayectoria"),
    "tractores": Perfil(("motor", "transmisión", "toma de fuerza", "apero"), "tracción a baja velocidad, transferencia de peso y estabilidad frente al vuelco", "trabajo transversal en pendiente con un implemento elevado", "vuelco lateral, atrapamiento en la toma de fuerza o pérdida de dirección", "tractor agrícola convencional frente a articulado", "bajar el implemento, reducir velocidad y escoger una trayectoria compatible"),
    "maquinaria-construccion": Perfil(("motor", "sistema hidráulico", "implemento", "suelo"), "estabilidad dependiente del centro de gravedad, apoyo y reacción del terreno", "excavación próxima a un borde con material cambiante", "vuelco, colapso del borde o ingreso de terceros al radio de acción", "excavadora frente a cargador frontal", "evaluar terreno, zona de exclusión y posición antes de accionar el implemento"),
    "barcos-mercantes": Perfil(("motor principal", "eje", "hélice", "casco y timón"), "inercia hidrodinámica: una orden de máquina o timón tarda en cambiar la trayectoria", "entrada a canal angosto con corriente transversal y tráfico", "abordaje o varada por decidir con referencias tardías", "portacontenedores frente a granelero", "planificar derrota, velocidad y punto de maniobra con margen suficiente"),
    "cruceros": Perfil(("generación eléctrica", "propulsión", "hélices o pods", "casco y gobierno"), "maniobrabilidad de gran masa combinada con viento lateral y efecto de aguas restringidas", "atraque con viento sobre una superestructura de gran superficie", "contacto con muelle o pérdida de separación por subestimar abatimiento", "crucero convencional frente a buque con propulsión azimutal", "coordinar propulsión, remolcadores y límites de viento antes de aproximar"),
    "acorazados": Perfil(("calderas o motores", "turbinas", "ejes y hélices", "casco blindado"), "compromiso histórico entre protección, potencia, alcance, estabilidad y potencia de fuego", "maniobra histórica simulada de una unidad pesada en formación", "reacción lenta y exposición causada por gran radio táctico y baja aceleración", "acorazado pre-dreadnought frente a dreadnought", "anticipar el movimiento considerando inercia, formación y campo de observación"),
    "portaviones": Perfil(("planta propulsora", "generación y catapulta", "cubierta de vuelo", "aeronave"), "integración de viento relativo, movimiento del buque y secuencia segura de cubierta", "recuperación simulada de aeronaves con cubierta ocupada parcialmente", "conflicto de trayectorias, objetos extraños o envolvente de viento inadecuada", "portaaviones CATOBAR frente a STOVL", "ordenar cubierta, rumbo y velocidad antes de iniciar la recuperación"),
    "submarinos": Perfil(("fuente de energía", "motor", "hélice o propulsor", "planos y tanques de lastre"), "equilibrio entre flotabilidad, peso, profundidad, trimado y control hidrodinámico", "cambio de profundidad manteniendo rumbo y discreción", "exceso de profundidad, pérdida de control o colisión por conciencia situacional limitada", "submarino diésel-eléctrico frente a nuclear", "coordinar velocidad, planos y lastre observando tendencia, no solo profundidad instantánea"),
    "aviones-pequenos": Perfil(("motor", "hélice", "flujo de aire", "alas y mandos"), "balance entre sustentación, peso, empuje y resistencia dentro de una envolvente limitada", "aproximación con viento cruzado y pista corta", "pérdida aerodinámica o salida de pista por velocidad y trayectoria inestables", "entrenador de ala alta frente a turismo de ala baja", "estabilizar aproximación y frustrar si no se cumplen criterios antes del umbral"),
    "aviones-pasajeros": Perfil(("motor", "empuje", "flujo de aire", "alas y controles"), "gestión de energía vertical y horizontal mediante actitud, empuje y configuración", "aproximación con cambio tardío de viento y una alerta de configuración", "continuar una aproximación inestable o automatizar sin comprender el modo activo", "avión de fuselaje estrecho frente a fuselaje ancho", "confirmar modo, energía y configuración; frustrar si la estabilidad no se recupera"),
    "aviones-combate": Perfil(("motor", "tobera", "flujo", "superficies y control de vuelo"), "intercambio entre energía cinética, altura, carga estructural y capacidad de giro", "maniobra simulada de alta carga con combustible limitado", "exceder envolvente, perder energía o conciencia situacional", "caza ligero monomotor frente a interceptor bimotor", "preservar margen de energía y carga antes de ordenar una maniobra"),
    "helicopteros": Perfil(("motor", "transmisión", "rotor principal", "empuje y control"), "sustentación del rotor condicionada por paso colectivo, cíclico, potencia y rotor de cola", "vuelo estacionario fuera de efecto suelo con temperatura elevada", "déficit de potencia, pérdida de rpm o control de guiñada", "helicóptero ligero frente a helicóptero de transporte", "comprobar potencia disponible y mantener una vía de escape antes del estacionario"),
    "drones": Perfil(("batería", "controladores", "motores y hélices", "actitud y trayectoria"), "el controlador estabiliza actitud, pero autonomía, enlace y entorno limitan la misión", "inspección próxima a una estructura con viento y señal GNSS degradada", "pérdida de enlace, deriva, impacto o invasión de espacio no autorizado", "multirrotor frente a ala fija", "definir límites de viento, batería, enlace, geocerca y retorno antes de despegar"),
    "cohetes": Perfil(("propelentes", "cámara", "tobera", "empuje y trayectoria"), "la aceleración depende de empuje menos peso y resistencia, mientras la masa disminuye", "ascenso educativo con cambio de etapa y viento en altura", "inestabilidad, desviación o cargas excesivas durante máxima presión dinámica", "cohete de combustible líquido frente a sólido", "evaluar trayectoria, estabilidad y condiciones de aborto antes del lanzamiento"),
    "transbordadores": Perfil(("motores principales", "propulsores sólidos", "vehículo orbital", "superficies de reentrada"), "una misión combina regímenes irreversibles: ascenso propulsado, órbita y planeo sin motor", "reentrada simulada con energía suficiente pero opciones de pista limitadas", "disipar mal la energía o salir del corredor térmico y geométrico", "configuración de lanzamiento frente a orbitador en planeo", "administrar energía y puntos de no retorno antes de cada fase"),
    "estacion-espacial": Perfil(("paneles solares", "distribución eléctrica", "soporte vital", "módulos y tripulación"), "equilibrio continuo de energía, atmósfera, calor y orientación orbital", "pérdida parcial de generación durante una actividad planificada", "degradación de soporte vital o energía por priorización tardía", "segmento presurizado frente a estructura externa", "aislar la falla y priorizar cargas esenciales antes de recuperar la misión"),
    "naves-espaciales": Perfil(("fuente de energía", "propulsión", "navegación y control", "órbita o trayectoria"), "pequeños cambios de velocidad producen cambios acumulativos de órbita y ventanas de encuentro", "maniobra de aproximación orbital con combustible de reserva limitado", "colisión o imposibilidad de retirada por quemado mal orientado o tardío", "cápsula tripulada frente a sonda robótica", "verificar marco de referencia, ventana, delta-v y opción de aborto antes del encendido"),
    "delorean": Perfil(("motor y alimentación ficticia", "transmisión", "ruedas", "sistema temporal"), "separación entre mecánica automotriz plausible y regla narrativa de velocidad y energía", "intento de alcanzar la condición temporal en una vía con espacio limitado", "confundir canon con física real y omitir los riesgos ordinarios del automóvil", "DeLorean de serie frente a máquina temporal ficticia", "declarar qué regla pertenece al relato y modelar aparte movimiento, energía y seguridad reales"),
    "caza-estelar": Perfil(("fuente de energía ficticia", "propulsión", "control de actitud", "trayectoria"), "contraste entre maniobra mostrada en el canon y conservación del momento en el espacio", "intercepción ficticia seguida de una maniobra de evasión", "trasladar aerodinámica atmosférica al vacío sin justificar la licencia narrativa", "vuelo atmosférico frente a vuelo espacial", "separar regla de universo, modelo físico elegido y retroalimentación al jugador"),
    "nave-exploracion": Perfil(("energía ficticia", "propulsión", "navegación", "misión científica"), "la exploración exige administrar incertidumbre, sensores, energía y distancia además de propulsión", "aproximación a un fenómeno desconocido con lecturas contradictorias", "perder capacidad de retirada al consumir energía o confiar en un único sensor", "crucero de exploración ficticio frente a sonda real", "establecer distancia de seguridad, redundancia de medición y criterio de retirada"),
    "nautilus": Perfil(("energía descrita en la obra", "motor", "hélice", "casco y timones"), "lectura doble: tecnología imaginada por Verne y principios reales de flotabilidad y presión", "inmersión narrativa cerca de relieve submarino", "colisión o exceso de profundidad al tomar la descripción literaria como procedimiento real", "Nautilus literario frente a submarino moderno", "citar el canon y contrastar cada maniobra con física y navegación reales"),
    "caza-transformable": Perfil(("fuente de energía ficticia", "actuadores de transformación", "propulsión", "configuración de vuelo o robot"), "cambiar de configuración altera masa aparente, control, resistencia y función narrativa", "transición simulada de vuelo a modo robot durante una misión", "ocultar discontinuidades físicas bajo una animación sin reglas de estado", "modo caza frente a modo robot", "definir condiciones, costos y límites de cada transición antes de simularla"),
    "halcon-milenario": Perfil(("reactor ficticio", "hiperimpulsor", "control de actitud", "trayectoria"), "contraste entre prestaciones canónicas y un modelo consistente de energía, inercia y navegación", "escape ficticio con hiperimpulsor degradado", "usar la velocidad narrativa como sustituto de decisiones y estados comprensibles", "vuelo sublumínico frente a salto hiperespacial", "hacer visibles prerrequisitos, fallas y consecuencias de cada modo de propulsión"),
    "sdf-1": Perfil(("energía ficticia", "propulsión", "transformación estructural", "nave y población"), "una nave-ciudad combina movilidad, transformación y continuidad de servicios", "transformación simulada mientras algunos sistemas están degradados", "tratar la transformación como efecto visual sin impactos en energía, estructura y habitabilidad", "modo crucero frente a configuración humanoide", "secuenciar transición, aislar servicios y representar costos operativos"),
    "estrella-de-la-muerte": Perfil(("reactor ficticio", "distribución", "propulsión y control", "estación"), "una megaestructura debe modelarse como red de subsistemas y dependencias, no como un solo vehículo", "falla simulada de distribución que afecta sectores distintos", "crear un sistema invulnerable o sin propagación comprensible de fallas", "estación móvil ficticia frente a estación orbital real", "mapear dependencias, redundancias y estados degradados antes de decidir"),
    "teletransportador": Perfil(("sensado ficticio", "codificación", "transmisión", "reconstrucción"), "la tecnología narrativa plantea continuidad, información, energía y verificación de destino", "transporte ficticio con señal degradada y destino parcialmente bloqueado", "presentar una ficción sin límites, fallas observables ni dilemas explícitos", "transporte convencional frente a teletransporte narrativo", "definir condiciones de autorización, aborto y evidencia de integridad"),
    "thunderbird-1": Perfil(("energía ficticia", "propulsión", "superficies de control", "trayectoria de respuesta"), "una aeronave de alerta rápida prioriza tiempo de llegada sin abandonar energía ni margen de aterrizaje", "despliegue de rescate a una pista corta con meteorología cambiante", "convertir velocidad narrativa en llegada segura sin plan de aproximación", "vuelo supersónico ficticio frente a jet ligero real", "separar crucero rápido de aproximación estabilizada y mantener alternativa"),
    "thunderbird-2": Perfil(("energía ficticia", "sustentación y propulsión", "bahía modular", "carga de rescate"), "la carga modular cambia masa, centro de gravedad, potencia y misión", "despegue vertical ficticio con módulo pesado de rescate", "ignorar cómo la carga modifica control, autonomía y zona de operación", "configuración vacía frente a módulo pesado", "recalcular margen y seleccionar zona antes de comprometer el aterrizaje"),
    "thunderbird-3": Perfil(("propelentes ficticios", "motores", "guiado", "trayectoria espacial"), "una misión de rescate espacial une lanzamiento, encuentro y reserva para retorno", "intercepción de una nave averiada con ventana temporal corta", "consumir la reserva durante la aproximación y perder capacidad de regreso", "ascenso atmosférico frente a encuentro orbital", "presupuestar combustible y criterios de aborto para cada fase"),
}


if len(PERFILES) != 41:
    raise RuntimeError(f"Se esperaban 41 perfiles pedagógicos y hay {len(PERFILES)}")
